changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
    authors:
      - github-actions
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Compatibility
      labels:
        - compatibility
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
